services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    # Sylius\Component\Channel\Context\ChannelContextInterface: '@sylius.context.channel.cached'

    Kreyu\SyliusPaymentFeePlugin\Form\Type\Calculator\FlatRateConfigurationType: ~

    Kreyu\SyliusPaymentFeePlugin\Model\Calculator\DelegatingCalculator:
        arguments:
            $registry: '@kreyu.payment_fee_plugin.registry.payment_calculator'

    Kreyu\SyliusPaymentFeePlugin\Model\Calculator\DelegatingCalculatorInterface: '@Kreyu\SyliusPaymentFeePlugin\Model\Calculator\DelegatingCalculator'

    Kreyu\SyliusPaymentFeePlugin\Form\Type\CalculatorChoiceType:
        arguments:
            $calculators: '%kreyu.payment_fee_plugin.payment_fee_calculators%'
        tags:
            -   name: form.type

    Kreyu\SyliusPaymentFeePlugin\Form\Extension\PaymentMethodTypeExtension:
        arguments:
            $calculatorRegistry: '@kreyu.payment_fee_plugin.registry.payment_calculator'
            $formTypeRegistry: '@kreyu.payment_fee_plugin.form_registry.payment_calculator'
        tags:
            -   extended_type: Sylius\Bundle\PaymentBundle\Form\Type\PaymentMethodType
                name: form.type_extension

    Kreyu\SyliusPaymentFeePlugin\Form\Extension\PaymentMethodChoiceTypeExtension:
        arguments:
            $calculatorRegistry: '@kreyu.payment_fee_plugin.registry.payment_calculator'
        tags:
            -   name: form.type_extension
                extended_type: Sylius\Bundle\PaymentBundle\Form\Type\PaymentMethodChoiceType

    kreyu.payment_fee_plugin.registry.payment_calculator:
        class: Sylius\Component\Registry\ServiceRegistry
        arguments:
            $context: payment fee calculator
            $className: Kreyu\SyliusPaymentFeePlugin\Model\Calculator\CalculatorInterface

    kreyu.payment_fee_plugin.form_registry.payment_calculator:
        class: Sylius\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    Kreyu\SyliusPaymentFeePlugin\Model\Calculator\FlatRateCalculator:
        tags:
            -   calculator: flat_rate
                form_type: Kreyu\SyliusPaymentFeePlugin\Form\Type\Calculator\ChannelBasedFlatRateConfigurationType
                label: 'kreyu_sylius_payment_fee_plugin.form.payment_calculator.flat_rate_configuration.label'
                name: Kreyu\SyliusPaymentFeePlugin\Model\Calculator\DelegatingCalculator

    Kreyu\SyliusPaymentFeePlugin\Model\PaymentChargesProcessor:
        arguments:
            $adjustmentFactory: '@sylius.factory.adjustment'
            $paymentChargesCalculator: '@Kreyu\SyliusPaymentFeePlugin\Model\Calculator\DelegatingCalculator'
        tags:
            -   name: sylius.order_processor
                priority: 0

    kreyu.payment_fee_plugin.order_processing.order_payment_processor.checkout:
        class: Sylius\Component\Core\OrderProcessing\OrderPaymentProcessor
        arguments:
            - '@sylius.order_payment_provider'
        tags:
            -   name: sylius.order_processor
                priority: 5

    kreyu.payment_fee_plugin.block_event_listener.admin.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@KreyuSyliusPaymentFeePlugin/Admin/_javascripts.html.twig'
        tags:
            -   event: sonata.block.event.sylius.admin.layout.javascripts
                method: onBlockEvent
                name: kernel.event_listener

    Kreyu\SyliusPaymentFeePlugin\Model\Taxation\Applicator\OrderPaymentTaxesApplicator:
        arguments:
            $calculator: '@sylius.tax_calculator'
            $adjustmentFactory: '@sylius.factory.adjustment'
            $taxRateResolver: '@sylius.tax_rate_resolver'

    kreyu.taxation.order_items_based_strategy:
        class: Sylius\Bundle\CoreBundle\Taxation\Strategy\TaxCalculationStrategy
        decorates: sylius.taxation.order_items_based_strategy
        tags:
            -   name: sylius.taxation.calculation_strategy
                type: order_items_based
                label: 'Order items based'
        arguments:
            $type: 'order_items_based'
            $applicators:
                - '@sylius.taxation.order_items_taxes_applicator'
                - '@sylius.taxation.order_shipment_taxes_applicator'
                - '@Kreyu\SyliusPaymentFeePlugin\Model\Taxation\Applicator\OrderPaymentTaxesApplicator'

    kreyu.taxation.order_item_units_based_strategy:
        class: Sylius\Bundle\CoreBundle\Taxation\Strategy\TaxCalculationStrategy
        decorates: sylius.taxation.order_item_units_based_strategy
        tags:
            -   name: sylius.taxation.calculation_strategy
                type: order_item_units_based
                label: 'Order item units based'
        arguments:
            $type: order_item_units_based
            $applicators:
                - '@sylius.taxation.order_item_units_taxes_applicator'
                - '@sylius.taxation.order_shipment_taxes_applicator'
                - '@Kreyu\SyliusPaymentFeePlugin\Model\Taxation\Applicator\OrderPaymentTaxesApplicator'
